### ISSUE TITLE
get-mcv1-sentences-test.sh , get-mcv7-sentences-test.sh and get-mcv1-singlewords-test.sh do not exist in folder ./bin/data

### ISSUE THREAD

**Issue by DogTian** [dijksterhuis/cleverSpeech#4]
when i run download.sh,it needs to run these three files, but I found that there are no these files in this directory. I want to know the specific contents of these three files, or how to run this project without docker.
Thank you!

**Comment by dijksterhuis** [comment]
heya @DogTian I recently refactored the python data ingress code so it will check for the presence of each data set and then download / extract as and when required rather than do everything up front in a shell script. So long as your dependencies are all good and you've got the model files then you should be good to go. Although you'll still need to install the cleverspeech python library with 
```
python3 -m pip install -e .
```
Probably best to do it all in a virtual environment for cleanliness sake (if you haven't already).

See [here](https://github.com/dijksterhuis/cleverspeech-py/blob/6a708e77a3ea9d8bef768977e055a492e3bdd45e/data/ingress/downloader.py) for the maybe download/extract python code and [here](https://github.com/dijksterhuis/cleverspeech-py/blob/6a708e77a3ea9d8bef768977e055a492e3bdd45e/config/arguments_parser.py#L19
) for the relevant command line arguments for the scripts (I think most of them are up to date now?!)

Will update the `download.sh` script though so it's less out of date.

**Fair warning:** There be dragons! This repo is basically my PhD in a repo (including all the mistakes, dead ends and failures). So there's weird and not particularly useful stuff in the `master` branch which may be a bit broken. 

For each script it's probably a good bet to first run `./cleverspeech/scripts/ctc-attacks.py --help` just to read through all the available options as some of the optional arguments require certain classes in a graph to work and/or are depreciated: `--pgd_rounding` doesn't do anything, for example.

**Comment by DogTian** [comment]
> heya @DogTian我最近重构了 python 数据入口代码，以便它检查每个数据集的存在，然后根据需要下载/提取，而不是在 shell 脚本中预先完成所有操作。只要您的依赖项都很好并且您已经有了模型文件，那么您就可以开始工作了。尽管您仍然需要安装cleverspeech python 库
> 
> ```
> python3 -m pip install -e .
> ```
> 
> 为了清洁起见，最好在虚拟环境中完成这一切（如果您还没有）。
> 
> 请参阅[此处](https://github.com/dijksterhuis/cleverspeech-py/blob/6a708e77a3ea9d8bef768977e055a492e3bdd45e/data/ingress/downloader.py)获取可能的下载/提取 python 代码和[此处](https://github.com/dijksterhuis/cleverspeech-py/blob/6a708e77a3ea9d8bef768977e055a492e3bdd45e/config/arguments_parser.py#L19)获取脚本的相关命令行参数（我认为它们中的大多数现在都是最新的？！）
> 
> 不过会更新`download.sh`脚本，这样它就不会过时了。
> 
> **公平警告：**有龙！这个 repo 基本上是我在 repo 中的博士（包括所有的错误、死胡同和失败）。所以`master`分支中有一些奇怪且不是特别有用的东西，可能有点坏。
> 
> 对于每个脚本，首先运行`./cleverspeech/scripts/ctc-attacks.py --help`只是为了通读所有可用选项可能是一个不错的选择，因为一些可选参数需要图中的某些类才能工作和/或折旧：`--pgd_rounding`例如，不做任何事情。
